name: Activate Unity License

on:
  workflow_dispatch:

jobs:
  activate:
    name: Activate Unity License
    runs-on: ubuntu-latest
    container:
      image: unityci/editor:ubuntu-6000.0.41f1-linux-il2cpp-3.1.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Activate Unity License
        uses: game-ci/unity-activate@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: 6000.0.41f1
